# Defines hosting/authentication
backend:
#  name: test-repo
#  name: git-gateway
#  branch: master
  name: github
  repo: bryanpizzillo/r4rcontent
  branch: master
  base_url: https://cms-auth.pizzillo.com

# Instead of just pushing directly to master,
# require some reviews and approvals 
publish_mode: editorial_workflow

media_folder: "assets/uploads"

# Define the content model
collections:
  - name: "resource" ## The type of object
    label: "Resource" ## The label used in the UI
    folder: "resources" ## Where the content is stored
    format: "yaml-frontmatter"
    create: true ## New items can be created.
    slug: "{{slug}}" ## The filename to create
    fields: # The fields
      - {label: "ID", name: "id", widget: "number" }
      - {label: "Title", name: "title", widget: "string" }
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Content", name: "body", widget: "markdown"}
      - label: "Tool Types"
        name: "toolTypes"
        widget: "list"
        default: []
        fields:
          - label: "Tool Type"
            name: "toolType"
            widget: "select"
            options: 
              - { label: "", value: "" }
              - { label: "", value: "" }
              - { label: "", value: "" }
              - { label: "", value: "" }
              - { label: "", value: "" }
              - { label: "", value: "" }
              - { label: "", value: "" }
      - label: "Divisions, Offices and Centers (DOCs)"
        name: "docs"
        widget: "list"
        default: []
        fields:
          - label: "DOC"
            name: "doc"
            widget: "select"
            options:
              - { label: "Division of Cancer Epidemiology and Genetics", value: "DCEG" }
              - { label: "Center for Bioinformatics and Information Technology", value: "CBIIT" }
      - label: "Points of Contact"
        name: "poc"
        widget: "list"
        default: []
        fields:
          - label: "Name"
            name: "name"
            widget: "object"
            fields:
              - {label: "Prefix", name: "prefix", widget: "string"}
              - {label: "First Name", name: "firstname", widget: "string"}
              - {label: "Middle Name", name: "middlename", widget: "string"}
              - {label: "Last Name", name: "lastname", widget: "string"}
              - {label: "Suffix", name: "suffix", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "E-Mail", name: "email", widget: "string"}      
